### ISSUE TITLE
Alternative solution

### ISSUE THREAD

**Issue by GrosSacASac** [tc39/proposal-promise-try#11]
> However, f is needlessly run asynchronously, on a future tick.

Maybe Promises should not needlessly run asynchronously in such cases.

The alternative solution would be to fix the Promise spec. _I heard other people in NodeJs community were also discussing this at some point_

**Comment by ljharb** [comment]
There are no discussions or viable changes that would alter this proposal or that sentence.

What you’re thinking of is reducing ticks in a different specific case.
