### ISSUE TITLE
[[Resolve]] / [[Reject]] call can throw when sourced from NewPromiseCapability(C)

### ISSUE THREAD

**Issue by linusg** [tc39/proposal-promise-try#14]
I think generally `! Call` is only safe for `NewPromiseCapability(%Promise%)`, e.g. as in https://tc39.es/ecma262/#sec-runtime-semantics-evaluateasyncfunctionbody

cf: https://tc39.es/ecma262/#sec-promise.reject

**Comment by ljharb** [comment]
ah, you're right, a subclass could be misbehaving. I'll update the spec to fix this.
