### ISSUE TITLE
Is this Stage 3?

### ISSUE THREAD

**Issue by foolip** [tc39/proposal-promise-try#21]
In [[blink-dev] Intent to Ship: Promise.try](https://groups.google.com/a/chromium.org/g/blink-dev/c/1cxpRmqIY44/m/7EDxh6NVAAAJ) @syg notes that this is actually stage 3, but the repo hasn't been updated.

**Comment by ljharb** [comment]
#15 is updated, but you're right I haven't yet updated the readme or spec. Thanks for the reminder.
